[project]
name = "csi"
version = "0.1.0"
description = "CLI for AWS CloudShell"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.37.12",
    "botocore>=1.37.12",
    "requests>=2.32.3",
    "shtab>=1.7.1",
]
